services:
  db:
    image: mariadb:11.3
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: Outhouse9-Purr0-Onscreen3-Harbor7
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  userservice:
    build: ./user-service
    depends_on:
      - db 
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/user_db
      SPRING_DATASOURCE_USERNAME: rick
      SPRING_DATASOURCE_PASSWORD: Roundworm1-Enjoyably6-Uphill9-Hurried5
    networks:
      - backend

  cardservice:
    build: ./card-service  
    depends_on:
      -db 
    ports: 
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/card_db
      SPRING_DATASOURCE_USERNAME: rick
      SPRING_DATASOURCE_PASSWORD: Roundworm1-Enjoyably6-Uphill9-Hurried5
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
